{% set name = "vcpkg" %}
{% set version = "2020.11-1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vcpkg/archive/{{ version }}.tar.gz
  sha256: dcae747fddfc1540b57d576afd2ad5191611013cce0bf30f184a1535c3d90fbe

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  run:
    - ninja
    - cmake
    - curl
    - git
    - unzip  # [unix]
    - tar    # [unix]
    - 7zip   # [win]

test:
  commands:
    - vcpkg --help || true             # [unix]
    - vcpkg.exe --help & exit 0        # [win]
    - vcpkg.exe install nlohmann-json  # [win]
    - vcpkg install nlohmann-json      # [osx]

about:
  home: https://github.com/microsoft/vcpkg
  license: MIT
  license_file: LICENSE.txt
  summary: https://github.com/microsoft/vcpkg

extra:
  recipe-maintainers:
    - wolfv
